### ISSUE TITLE
数据来源

### ISSUE THREAD

**Issue by ericzikun** [JZK00/InfoVis-2022#1]
请问展示的具体数据有来源网址吗，比如被占地点、制裁等等？谢谢

**Comment by JZK00** [comment]
您好，数据来源比较杂乱，有一些数据来源的网址如：http://app.people.cn/h5/topic/subject_normal/771；https://index.minfin.com.ua/；http://www.customs.gov.cn/ 等。还有一些是内部数据，或者分析数据。谢谢~
